name: flutter_lesson
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.3
  shimmer: ^2.0.0
  carousel_slider: 
    git: https://github.com/serenader2014/flutter_carousel_slider.git
    
   

cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/fonts/
  - assets/images/
  fonts:
  - family: ofont_Garet
    fonts:
       - asset: assets/fonts/ofont_Garet.ttf
         weight: 300

